apiVersion: v1
kind: Secret
metadata:
  name: service-secrets
  namespace: {{ .Values.namespace }}
type: Opaque
data:
  MONGO_USERNAME: {{ .Values.mongodb.username | b64enc }}
  MONGO_PASSWORD: {{ .Values.mongodb.password | b64enc }}
  MONGO_HOST: {{ .Values.mongodb.host | b64enc }}
  MONGO_PORT: {{ .Values.mongodb.port | b64enc }}
  MONGO_DB: {{ .Values.mongodb.database | b64enc }}
  JWT_SECRET: {{ .Values.jwt.secret | b64enc }}
  REDIS_HOST: {{ .Values.redis.host | b64enc }}
  REDIS_PORT: {{ .Values.redis.port | b64enc }}
  REDIS_PASSWORD: {{ .Values.redis.password | b64enc }}
  RABBITMQ_HOST: {{ .Values.rabbitmq.host | b64enc }}
  RABBITMQ_PORT: {{ .Values.rabbitmq.port | b64enc }}
  RABBITMQ_USERNAME: {{ .Values.rabbitmq.username | b64enc }}
  RABBITMQ_PASSWORD: {{ .Values.rabbitmq.password | b64enc }}
  RABBITMQ_EXCHANGE: {{ .Values.rabbitmq.exchange | b64enc }}
  RABBITMQ_USER_QUEUE: {{ .Values.rabbitmq.queue_user | b64enc }}
  RABBITMQ_AUTH_QUEUE: {{ .Values.rabbitmq.queue_auth | b64enc }}
  RABBITMQ_POSTS_QUEUE: {{ .Values.rabbitmq.queue_posts | b64enc }}
  RABBITMQ_REGISTER_ROUTINGKEY: {{ .Values.rabbitmq.routing_key_register | b64enc }}
  RABBITMQ_DELETE_ROUTINGKEY: {{ .Values.rabbitmq.routing_key_delete | b64enc }}

