apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.appName }}
  namespace: {{ .Values.namespace }}
spec:
  ports:
    - port: {{ .Values.appPort }}
      targetPort: 8080
  selector:
    app: {{ .Values.appName }}

